//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Params.
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to upload .
        /// </summary>
        public static string AreYouSureYouWantToUpload {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto WP.
        /// </summary>
        public static string AutoWP {
            get {
                return ResourceManager.GetString("AutoWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad KML File :.
        /// </summary>
        public static string Bad_KML_File {
            get {
                return ResourceManager.GetString("Bad_KML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Vision Position.
        /// </summary>
        public static string Bad_Vision_Position {
            get {
                return ResourceManager.GetString("Bad_Vision_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Accel Health.
        /// </summary>
        public static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad AHRS.
        /// </summary>
        public static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Baro Health.
        /// </summary>
        public static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Compass Health.
        /// </summary>
        public static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Lat/Lng.
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad GPS Signal Health.
        /// </summary>
        public static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Gyro Health.
        /// </summary>
        public static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad LiDAR Health.
        /// </summary>
        public static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Logging.
        /// </summary>
        public static string BadLogging {
            get {
                return ResourceManager.GetString("BadLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad OptFlow Health.
        /// </summary>
        public static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad or No Terrain Data.
        /// </summary>
        public static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basic Tuning.
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These are beta firmware, use at your own risk!!!.
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not connect to com port and detect board type.
        /// </summary>
        public static string CanNotConnectToComPortAnd {
            get {
                return ResourceManager.GetString("CanNotConnectToComPortAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot graph this field.
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant detect your Board version. Please check your cabling.
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Throttle.
        /// </summary>
        public static string ChangeThrottle {
            get {
                return ResourceManager.GetString("ChangeThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checking .
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check port settings or Port in use?.
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click when Done.
        /// </summary>
        public static string Click_when_Done {
            get {
                return ResourceManager.GetString("Click_when_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Command failed to execute
        ///.
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication Error - no connection.
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a compass variance.
        /// </summary>
        public static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONNECT.
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect Failed.
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connecting Mavlink.
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Converting bin to log.
        /// </summary>
        public static string Converting_bin_to_log {
            get {
                return ResourceManager.GetString("Converting_bin_to_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description: .
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detected a .
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detecting Board Version.
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISCONNECT.
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to load this into the flight data screen?.
        /// </summary>
        public static string Do_you_want_to_load_this_into_the_flight_data_screen {
            get {
                return ResourceManager.GetString("Do_you_want_to_load_this_into_the_flight_data_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded from internet.
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading from Internet.
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ensure your props are not on the Plane/Quad.
        /// </summary>
        public static string EnsurePropsNotOn {
            get {
                return ResourceManager.GetString("EnsurePropsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue?.
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epprom format changed ({0) vs {1}).
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error binding.
        /// </summary>
        public static string Error_binding {
            get {
                return ResourceManager.GetString("Error_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error closing log files.
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error communicating with the autopilot.
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Connecting
        ///.
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This feature is not enabled in your firmware..
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading firmware file.
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error receiving log list.
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no responce from MAV.
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not connected..
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error receiving list
        ///.
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: command rejected by MAV.
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error renaming file.
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error setting parameter .
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set {0} Failed.
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error uploading firmware.
        /// </summary>
        public static string ErrorUploadingFirmware {
            get {
                return ResourceManager.GetString("ErrorUploadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extended Tuning.
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create ground station log - wont log this session.
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to connect to SITL instance.
        /// </summary>
        public static string Failed_to_connect_to_SITL_instance {
            get {
                return ResourceManager.GetString("Failed_to_connect_to_SITL_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to download the SITL image..
        /// </summary>
        public static string Failed_to_download_the_SITL_image {
            get {
                return ResourceManager.GetString("Failed_to_download_the_SITL_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed download.
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed read HEX.
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to read firmware.hex :.
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed upload.
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FailSafe.
        /// </summary>
        public static string FailSafe {
            get {
                return ResourceManager.GetString("FailSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flight Modes.
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full Parameter List.
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full Parameter Tree.
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoFence.
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geofence Breach.
        /// </summary>
        public static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting .
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting FW List.
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting FW Version.
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting Params.
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting Params....
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting updated parameters.
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Got param .
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid home location.
        /// </summary>
        public static string Invalid_home_location {
            get {
                return ResourceManager.GetString("Invalid_home_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Alt.
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid BaudRate.
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Board Type.
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Cert.
        /// </summary>
        public static string InvalidCert {
            get {
                return ResourceManager.GetString("InvalidCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Field.
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid FileName.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid number entered
        ///.
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Pan Range.
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid PortName.
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Tilt Range.
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Update Rate.
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link Stats.
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load data.
        /// </summary>
        public static string Load_data {
            get {
                return ResourceManager.GetString("Load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please click ok and move the autopilot around all axises in a circular motion.
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mavlink Connecting....
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are missing data points. do you want to run the calibration anyway?.
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Firmware.
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New firmware available
        ///.
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No firmware available for this board!.
        /// </summary>
        public static string No_firmware_available_for_this_board {
            get {
                return ResourceManager.GetString("No_firmware_available_for_this_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No valid heartbeats read from port.
        /// </summary>
        public static string No_valid_heartbeats_read_from_port {
            get {
                return ResourceManager.GetString("No_valid_heartbeats_read_from_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No valid sik radio.
        /// </summary>
        public static string No_valid_sik_radio {
            get {
                return ResourceManager.GetString("No_valid_sik_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No FMT message for .
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No need to upload. already on the board.
        /// </summary>
        public static string NoNeedToUpload {
            get {
                return ResourceManager.GetString("NoNeedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO RC Receiver.
        /// </summary>
        public static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not available when used as a windows store app.
        /// </summary>
        public static string Not_available_when_used_as_a_windows_store_app {
            get {
                return ResourceManager.GetString("Not_available_when_used_as_a_windows_store_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtain From Module.
        /// </summary>
        public static string ObtainFromModule {
            get {
                return ResourceManager.GetString("ObtainFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Onboard OSD.
        /// </summary>
        public static string OnboardOSD {
            get {
                return ResourceManager.GetString("OnboardOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only 1 Heatbeat Received.
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting.
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Param refresh is required - Please press F5
        ///old #{0}  new #{1}.
        /// </summary>
        public static string ParamRefreshRequired {
            get {
                return ResourceManager.GetString("ParamRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planner.
        /// </summary>
        public static string Planner {
            get {
                return ResourceManager.GetString("Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please connect first.
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please connect and backup your config in the configuration tab..
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please load a valid file.
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a cell first.
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please unplug the board, and then press OK and plug back in.
        ///Mission Planner will look for 30 seconds to find the board.
        /// </summary>
        public static string PleaseUnplugTheBoardAnd {
            get {
                return ResourceManager.GetString("PleaseUnplugTheBoardAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///Please upgrade.
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait for the musical tones to finish before clicking OK.
        /// </summary>
        public static string PleaseWaitForTheMusicalTones {
            get {
                return ResourceManager.GetString("PleaseWaitForTheMusicalTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pos horiz variance.
        /// </summary>
        public static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pos vert variance.
        /// </summary>
        public static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucessfully programmed.
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put the transmitter in bind mode. Receiver is waiting..
        /// </summary>
        public static string Put_the_transmitter_in_bind_mode__Receiver_is_waiting {
            get {
                return ResourceManager.GetString("Put_the_transmitter_in_bind_mode__Receiver_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw Param Warning.
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings.
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading Hex.
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading Hex File.
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received List.
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a run anyway.
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanning File.
        /// </summary>
        public static string Scanning_File {
            get {
                return ResourceManager.GetString("Scanning_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a comport.
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Here.
        /// </summary>
        public static string SetHere {
            get {
                return ResourceManager.GetString("SetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show me again?.
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard Params.
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your model is still moving are you sure you want to disconnect?.
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terrain alt variance.
        /// </summary>
        public static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0).
        /// </summary>
        public static string ThisBoardHasBeenRetired {
            get {
                return ResourceManager.GetString("ThisBoardHasBeenRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout waiting for autoscan/no mavlink device connected.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracker Home.
        /// </summary>
        public static string TrackerHome {
            get {
                return ResourceManager.GetString("TrackerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trunk.
        /// </summary>
        public static string Trunk {
            get {
                return ResourceManager.GetString("Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These are the latest trunk firmware, use at your own risk!!!.
        /// </summary>
        public static string TrunkWarning {
            get {
                return ResourceManager.GetString("TrunkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to connect.
        ///Timeout in {0}.
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Units: {0}{1}.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Found
        ///
        ///Do you wish to update now? .
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No update available..
        /// </summary>
        public static string UpdateNotFound {
            get {
                return ResourceManager.GetString("UpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Complete.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading {0} bytes to Board:.
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload succeeded, but verify failed: exp {0} got {1} at .
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Params.
        /// </summary>
        public static string User_Params {
            get {
                return ResourceManager.GetString("User_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a velocity variance.
        /// </summary>
        public static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Complete.
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Firmware.
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter.
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration..
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log..
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning rally points are located greater than RALLY_LIMIT_KM.
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        ///.
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are using unsupported hardware.
        ///This board does not contain a valid certificate of authenticity.
        ///Please contact your hardware vendor about signing your hardware..
        /// </summary>
        public static string YouAreUsingUnsupportedHardware {
            get {
                return ResourceManager.GetString("YouAreUsingUnsupportedHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom To.
        /// </summary>
        public static string Zoom_To {
            get {
                return ResourceManager.GetString("Zoom_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom to the center or the loaded file?.
        /// </summary>
        public static string Zoom_to_the_center_or_the_loaded_file {
            get {
                return ResourceManager.GetString("Zoom_to_the_center_or_the_loaded_file", resourceCulture);
            }
        }
    }
}
