//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMap.NET.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMap.NET.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMap.
        /// </summary>
        internal static string AMap {
            get {
                return ResourceManager.GetString("AMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMapSatellite.
        /// </summary>
        internal static string AMapSatellite {
            get {
                return ResourceManager.GetString("AMapSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BingHybridMap.
        /// </summary>
        internal static string BingHybridMap {
            get {
                return ResourceManager.GetString("BingHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BingMap.
        /// </summary>
        internal static string BingMap {
            get {
                return ResourceManager.GetString("BingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BingSatelliteMap.
        /// </summary>
        internal static string BingSatelliteMap {
            get {
                return ResourceManager.GetString("BingSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleChinaHybridMap.
        /// </summary>
        internal static string GoogleChinaHybridMap {
            get {
                return ResourceManager.GetString("GoogleChinaHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleChinaMap.
        /// </summary>
        internal static string GoogleChinaMap {
            get {
                return ResourceManager.GetString("GoogleChinaMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleChinaSatelliteMap.
        /// </summary>
        internal static string GoogleChinaSatelliteMap {
            get {
                return ResourceManager.GetString("GoogleChinaSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleChinaTerrainMap.
        /// </summary>
        internal static string GoogleChinaTerrainMap {
            get {
                return ResourceManager.GetString("GoogleChinaTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleHybridMap.
        /// </summary>
        internal static string GoogleHybridMap {
            get {
                return ResourceManager.GetString("GoogleHybridMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleMap.
        /// </summary>
        internal static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleSatelliteMap.
        /// </summary>
        internal static string GoogleSatelliteMap {
            get {
                return ResourceManager.GetString("GoogleSatelliteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GoogleTerrainMap.
        /// </summary>
        internal static string GoogleTerrainMap {
            get {
                return ResourceManager.GetString("GoogleTerrainMap", resourceCulture);
            }
        }
    }
}
