//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.Controls {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HUDT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HUDT() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Controls.HUDT", typeof(HUDT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ARMED.
        /// </summary>
        public static string ARMED {
            get {
                return ResourceManager.GetString("ARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AS .
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bat .
        /// </summary>
        public static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISARMED.
        /// </summary>
        public static string DISARMED {
            get {
                return ResourceManager.GetString("DISARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILSAFE.
        /// </summary>
        public static string FAILSAFE {
            get {
                return ResourceManager.GetString("FAILSAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Int32 similar a 5.
        /// </summary>
        public static int FailsafeH {
            get {
                object obj = ResourceManager.GetObject("FailsafeH", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arial.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: No GPS.
        /// </summary>
        public static string GPS0 {
            get {
                return ResourceManager.GetString("GPS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: No Fix.
        /// </summary>
        public static string GPS1 {
            get {
                return ResourceManager.GetString("GPS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: 2D Fix.
        /// </summary>
        public static string GPS2 {
            get {
                return ResourceManager.GetString("GPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: 3D Fix.
        /// </summary>
        public static string GPS3 {
            get {
                return ResourceManager.GetString("GPS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: 3D dgps.
        /// </summary>
        public static string GPS4 {
            get {
                return ResourceManager.GetString("GPS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: rtk Float.
        /// </summary>
        public static string GPS5 {
            get {
                return ResourceManager.GetString("GPS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS: rtk Fixed.
        /// </summary>
        public static string GPS6 {
            get {
                return ResourceManager.GetString("GPS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GS .
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NE.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NW.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SE.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SW.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
    }
}
